name: Deploy Static Web - Supattarawadee Khunphetrsri 049

on:
  push:
    branches:
      - main   # หาก branch หลักใน GitHub คุณชื่อ master ให้เปลี่ยนคำว่า main เป็น master ครับ

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ใช้ Action ตามรูปแบบที่โจทย์ระบุ (actions/ชื่อนักศึกษา-รหัส3ตัวหลัง)
      - name: Checkout Code
        uses: actions/SupattarawadeeKhunphetrsri-049@v4

      # Deploy ไปยัง GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./