name: Deploy Static Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
   steps:
      # ใช้ Action สำเร็จรูปตามชื่อนักศึกษาและรหัสที่กำหนดในโจทย์ข้อ 2
      - name: Checkout repository
       uses: actions/checkout@v4

      # ตั้งค่าระบบ GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # อัปโหลดไฟล์ทั้งหมดในโฟลเดอร์หลักขึ้นระบบ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # ทำการ Deploy เว็บไซต์จริงไปยัง GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
